### ISSUE TITLE
Local File Obfuscation

### ISSUE THREAD

**Issue by anthonysharpy** [anthonysharpy/sandbank#36]
Need an option to obfuscate local files.

**Comment by Tankonyako** [comment]
I think this can be solved with encryption. It would be great to incorporate asymmetric encryption, where data is encrypted on the server and can be decrypted by the client at any time. Additionally, we could use a method that stores data on the client but decrypts and signs it on the server. This dual approach enhances security and flexibility in managing sensitive information.

**Comment by anthonysharpy** [comment]
@Tankonyako Sorry, I only just saw this comment for some reason

> I think this can be solved with encryption. It would be great to incorporate asymmetric encryption, where data is encrypted on the server and can be decrypted by the client at any time.

This is definitely possible, but I think the key is figuring out what the real-life use case would be

The only one I can think of is if the data was being stored on the client so that the same data worked across multiple servers. In this case you might want to encrypt it. However I sort of feel that in this case developers would probably rather store stuff in the cloud, since if the user deletes their data/reinstalls the game, their data will be lost, and if that data was important enough to encrypt, then that is probably a big deal for them
